# -*- coding: utf-8 -*-
"""Apriori suggestion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sy7pa9jHf-mRUCOwolgyuOenalcpmyeE
"""

!pip install apyori

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset=pd.read_csv('BigBasket.csv',header=None)
transactions=[]
for i in range(0,7219):
  transactions.append([str(dataset.values[i,j]) for j in range(0,20)])

from apyori import apriori
basket_intelligence=apriori(transactions=transactions,min_support=0.003,min_confidence=0.2,min_lift=3,min_length=2,max_length=2)

results=list(basket_intelligence)
results

def inspect(results):
  product1=[tuple(result[2][0][0])[0] for result in results]
  product2=[tuple(result[2][0][1])[0] for result in results]
  supports=[result[1] for result in results]
  confidences=[result[2][0][2] for result in results]
  lifts=[result[2][0][3] for result in results]
  return list(zip(product1,product2,supports,confidences,lifts))
DataFrame_intelligence=pd.DataFrame(inspect(results),columns=['product1','product2','support','confidence','lift'])

DataFrame_intelligence

DataFrame_intelligence.nlargest(n=10,columns='lift')

