# -*- coding: utf-8 -*-
"""netflix suggestion ECLAT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZA9vhMR4N9PNZls38C3RRH95wEa9-ieo
"""

!pip install apyori

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

try:
  dataset = pd.read_csv('Netflix.csv', header=None, encoding='latin-1')
except UnicodeDecodeError:
    try:
      dataset = pd.read_csv('Netflix.csv', header=None, encoding='ISO-8859-1')
    except UnicodeDecodeError:
      print("Could not open file with encoding: 'latin-1' or 'ISO-8859-1'")
      exit()
transactions = []
for i in range(0, 7466):
    transactions.append([str(dataset.values[i, j]) for j in range(0, 20)])

from apyori import apriori
rules=apriori(transactions=transactions,min_support=0.003,min_confidence=0.2,min_lift=3,min_length=2,max_length=2)

results=list(rules)

results

def inspect(results):
  lhs=[tuple(result[2][0][0])[0] for result in results]
  rhs=[tuple(result[2][0][1])[0] for result in results]
  supports=[result[1] for result in results]
  return list(zip(lhs,rhs,supports))
DataFrame_intelligence=pd.DataFrame(inspect(results),columns=['movie 1','movie 2','support'])

DataFrame_intelligence

DataFrame_intelligence.nlargest(n=10,columns='support')